[package]
name = "schmides"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = {git = "https://github.com/onsdagens/egui.git", branch = "patch-0.31.1-svgs"}
egui = {git = "https://github.com/onsdagens/egui.git", branch = "patch-0.31.1-svgs"}
egui_extras = {git = "https://github.com/onsdagens/egui.git", branch = "patch-0.31.1-svgs", features=["svg", "svg_text","svg_images", "all_loaders"]}
rfd = "0.17.2"

[profile.release]
lto = true
strip = "debuginfo"
